# Generated by Django 5.1 on 2024-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='نام برند')),
                ('brand_country', models.CharField(max_length=200, verbose_name='کشور برند')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='مدل')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='قیمت')),
                ('color', models.CharField(blank=True, default='Black', max_length=200, verbose_name='رنگ')),
                ('screen_size', models.FloatField(blank=True, default=5.0, verbose_name='اندازه صفحه')),
                ('is_available', models.BooleanField(blank=True, choices=[(True, 'موجود'), (False, 'ناموجود')], default=True, verbose_name='موجودی')),
                ('creator_country', models.CharField(blank=True, default='China', max_length=200, verbose_name='کشور سازنده')),
            ],
        ),
    ]
