# Generated by Django 5.1 on 2024-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=200, unique=True, verbose_name='مدل'),
        ),
    ]
