# Generated by Django 5.1 on 2024-08-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapi', '0002_alter_phone_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, default='Black', max_length=200, verbose_name='رنگ'),
        ),
    ]
