# Generated by Django 5.1 on 2024-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapi', '0004_alter_phone_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='creator_country',
            field=models.CharField(default='China', max_length=200, verbose_name='کشور سازنده'),
        ),
    ]
