# Generated by Django 5.1 on 2024-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapi', '0005_alter_phone_creator_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='creator_country',
            field=models.CharField(blank=True, default='China', max_length=200, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_available',
            field=models.BooleanField(blank=True, choices=[(True, 'موجود'), (False, 'ناموجود')], default=True, verbose_name='موجودی'),
        ),
    ]
